# -*- coding: utf-8 -*-
print("Welcome to the Finnish practice game!")

word_list = {
    "Olla": "To be",
    "Mennä": "To go",
    "Tulla": "To come",
    "Tehdä": "To do",
    "Syödä": "To eat",
    "Juoda": "To drink",
    "Puhua": "To speak",
    "Ostaa": "To buy",
    "Asua": "To live (reside)",
    "Rakentaa": "To build",
    "Kirjoittaa": "To write",
    "Lukea": "To read",
    "Nukkua": "To sleep",
    "Tanssia": "To dance",
    "Tuntea": "To know (person), to feel",
    "Antaa": "To give",
    "Viedä": "To take (something somewhere)",
    "Tuoda": "To bring",
    "Pitää": "To like, to hold",
    "Harrastaa": "To practice, to be interested in",
    "Pestä": "To wash",
    "Ajaa": "To drive, to ride",
    "Istua": "To sit",
    "Seisoa": "To stand",
    "Herätä": "To wake up",
    "Avata": "To open",
    "Sulkea": "To close",
    "Olla kiireinen": "To be busy",
    "Kävellä": "To walk",
    "Tulla kotiin": "To come home",
    "Etsiä": "To search",
    "Löytää": "To find",
    "Maksaa": "To pay",
    "Vastata": "To answer",
    "Kuunnella": "To listen",
    "Nauraa": "To laugh",
    "Itkeä": "To cry",
    "Opiskella": "To study",
    "Soittaa": "To call, to play (an instrument)",
    "Työskennellä": "To work",
    "Puhua puhelimessa": "To talk on the phone",
    "Tavata": "To meet",
    "Pysyä": "To stay",
    "Laulaa": "To sing",
    "Hymyillä": "To smile",
    "Rakastaa": "To love",
    "Vastustaa": "To resist",
    "Tarkistaa": "To check",
    "Lähteä": "To leave",
    "Pouta": "Fair weather",
    "Ylös": "Up",
    "Tyhmä": "Stupid",
    "Tyyli": "Style",
    "Pelätä": "To fear",
    "Hella": "Stove",
    "Nuori": "Young",
    "Hellä": "Gentle",
    "Tuuli": "Wind",
    "Nyöri": "Cord",
    "Pöytä": "Table",
    "Tuo": "That",
    "Kylmä": "Cold",
    "Pelata": "To play (a game)",
    "Kulma": "Corner",
    "Tuhma": "Naughty",
    "Ulos": "Out",
    "Työ": "Work",
    "Maito": "Milk",
    "Jäätelö": "Ice cream",
    "Kakku": "Cake",
    "Mehu": "Juice",
    "Pöytälamppu": "Table lamp",
    "Ruokapöytä": "Dining table",
    "Rullaverho": "Roller blind",
    "Vaatekaappi": "Wardrobe",
    "Kirjahylly": "Bookshelf",
    "Parisänky": "Double bed",
    "Työtuoli": "Office chair",
    "Päiväpeitto": "Bedspread"
}

for finnish, english in word_list.items():
    print(f"What is the Finnish translation of '{english}'?")
    answer = input("Your answer: ")
    
    if answer.strip().lower() == finnish.lower():
        print("Correct!")
    else:
        print(f"Wrong! The correct answer is: {finnish}")
    
    print()
    